# Generated by Django 4.0.6 on 2023-02-08 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=b'I01\n')),
                ('host', models.CharField(max_length=30, unique=b'I01\n')),
                ('puerto', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'BaseDeDatos',
                'db_table': 'BASEDEDATOS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(max_length=100, unique=b'I01\n')),
                ('correogrupal', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'db_table': 'DEPTO',
                'ordering': ['depto'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, unique=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Direcciones Administrativas',
                'db_table': 'DIRECCION',
                'ordering': ['direccion'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'EMPRESA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_usuario', models.IntegerField()),
                ('tiempo_ejecucionsegundo', models.IntegerField()),
                ('acceso', models.CharField(choices=[('WEB', 'Web'), ('DESKTOP', 'Desktop')], max_length=50, null=True)),
                ('Objetivo', models.CharField(max_length=200)),
                ('bases_de_datos', models.ManyToManyField(to='webapp.basededatos')),
                ('depto_utilizan', models.ManyToManyField(to='webapp.depto')),
                ('desarrolladopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.empresa')),
            ],
            options={
                'verbose_name_plural': 'Entidades',
                'db_table': 'ENTIDAD',
                'ordering': ['id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=b'I01\n')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'ESTADO',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='LenguajeProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Lenguajes De Programación',
                'db_table': 'LENGUAJEPROGRAMACION',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PalabrasClaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Palabras Claves',
                'db_table': 'PALABRASCLAVES',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('flota', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'PERSONA',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=b'I01\n')),
            ],
            options={
                'verbose_name_plural': 'Sistemas Operativos',
                'db_table': 'SISTEMAOPERATIVO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=b'I01\n')),
                ('categoria', models.CharField(choices=[('ENTIDAD', 'Entidad'), ('BASEDEDATOS', 'baseDeDatos')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'db_table': 'TIPO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioLider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.ManyToManyField(to='webapp.entidad')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.persona')),
            ],
            options={
                'verbose_name_plural': 'Usuarios Lideres',
                'db_table': 'USUARIOLIDER',
                'ordering': ['persona'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('ticketenkace', models.IntegerField()),
                ('objetivo_solicitud', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('extension', models.IntegerField()),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('flota_solicitante', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.depto')),
                ('tipoentidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.tipo')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'SOLICITUD',
                'ordering': ['nombre', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Manejador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ipservidor', models.CharField(max_length=50)),
                ('estado_manejador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.estado')),
            ],
            options={
                'verbose_name_plural': 'Manejadores',
                'db_table': 'MANEJADOR',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HManejador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('Estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.estado')),
                ('manejador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.manejador')),
            ],
            options={
                'verbose_name_plural': 'Historial Manejadores',
                'db_table': 'HMANEJADOR',
                'ordering': ['manejador'],
            },
        ),
        migrations.CreateModel(
            name='HBasededatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('Estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.estado')),
                ('bd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.basededatos')),
            ],
            options={
                'verbose_name_plural': 'Historial Base de Datos',
                'db_table': 'HBASEDEDATOS',
                'ordering': ['bd'],
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(max_length=100, unique=b'I01\n')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.direccion')),
            ],
            options={
                'verbose_name_plural': 'Gerencias',
                'db_table': 'GERENCIA',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='manejador',
            field=models.ManyToManyField(to='webapp.manejador'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='palabrasclaves',
            field=models.ManyToManyField(to='webapp.palabrasclaves'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DeptoResponsable', to='webapp.depto'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='sistemaoperativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.sistemaoperativo'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipoentidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.tipo'),
        ),
        migrations.AddField(
            model_name='depto',
            name='gerencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.gerencia'),
        ),
        migrations.AddField(
            model_name='basededatos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.estado'),
        ),
    ]
