# Generated by Django 4.0.6 on 2023-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='ruta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='acceso',
            field=models.CharField(choices=[('CITRIX', 'CITRIX'), ('DESKTOP', 'Desktop'), ('WEB', 'Web')], max_length=50, null=True),
        ),
    ]
