# Generated by Django 4.0.6 on 2024-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_entidad_ruta_alter_entidad_rutamanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='ruta',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
